name: Test JDK 21 on all OS's

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 21 ]
        os: [windows-latest, macOS-latest, ubuntu-latest]
        distribution: [ temurin ]
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up ${{ matrix.distribution }} JDK ${{ matrix.java_version }} on ${{ matrix.os }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: ${{ matrix.distribution }}

      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Test Docker
        run: |
          docker version
          docker info

      - name: Test
        run: sh ./gradlew check --stacktrace
  publish:
    needs: [ test ]
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Test Docker
        run: |
          docker version
          docker info

      - name: Publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.central_username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.central_password }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signing_key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signing_key_password }}
        run: sh ./gradlew publish --no-configuration-cache